### ISSUE TITLE
Make a test script pls

### ISSUE THREAD

**Issue by osdiab** [kevinshin/skvlr#2]
@rasmusrygaard we need you `Makefiles` are scary @anna-saplitski

**Comment by rasmusrygaard** [comment]
How do we want this set up? Just let client files link against the library so you only need to #include and update the makefile with source files?

**Comment by anna-saplitski** [comment]
That would be great.

**Comment by rasmusrygaard** [comment]
Sweet, all done. `make test` will build `bin/test` which currently implements a full test suite minus all the tests.
